version: '3.8'

services:
  api:
    image: rodcordeiro/mathly-api:latest
    container_name: mathly_api
    restart: unless-stopped
    ports:
      - '3341:80'
    env_file:
      - .env
    networks:
      - mathly
    logging:
      driver: "json-file"  # You can choose a different driver if needed
      options:
        max-size: "2m"  # Maximum size of a single log file
        max-file: "2"    # Maximum number of log files to retain

networks:
  mathly:
    driver: bridge
